theme: jekyll-theme-minimal
timezone: America/Argentina/Buenos_Aires
permalink: /blog/:year/:title/
title: my coding side
description: A short description of your site's purpose
logo: /assets/img/profileb-1.jpg
show_downloads: false