theme: jekyll-theme-minimal
timezone: America/Argentina/Buenos_Aires
permalink: /blog/:year/:title/
title: algorithmic Me
description: >-
        I do lot of things, here I share my algorithmic side <a href="https://rvalla.github.io/index">(eng)</a>. -
        Hago muchas cosas, aquí comparto mi costado algorítmico <a href="https://rvalla.github.io/index_es">(es)</a>.
logo: /assets/img/profileb-4.jpg
show_downloads: false