theme: jekyll-theme-minimal
timezone: America/Argentina/Buenos_Aires
permalink: /blog/:year/:title/
email: rodrigovalla@protonmail.ch
title: algorithmic Me
author: Rodrigo Valla
description: >-
        Here is my algorithmic side (<a href="https://rvalla.github.io/index">eng</a>).<br>
        Aquí está mi costado algorítmico (<a href="https://rvalla.github.io/index_es">es</a>).
logo: /assets/img/perfil_1.jpg
show_downloads: false